# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext
            cost: 12
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: 123
                        roles: 'ROLE_USER'
                    admin:
                        password: 123
                        roles: 'ROLE_ADMIN'
    role_hierarchy:
      ROLE_ADMIN: ROLE_USER
    access_control:
        # require ROLE_ADMIN for /admin*

        - { path: ^/api/hotels, roles: ROLE_USER }
        - { path: ^/api/users, roles: ROLE_ADMIN }

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            entry_point: custom_basic_authentication_entry_point
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
