#%RAML 1.0
title: ira-api
version: v1
mediaType: application/json
schemas:
  error:           !include schemas/error.json
  users:           !include schemas/users.json
  user:            !include schemas/user.json
  hotels:          !include schemas/hotels.json
  hotel:           !include schemas/hotel.json
  rooms:           !include schemas/rooms.json
  room:            !include schemas/room.json
  reservations:    !include schemas/reservations.json
  reservation:     !include schemas/reservation.json


/users:
  get:
    responses:
      200:
        description: Retrieve the list of users.
        body:
          schema: users
  post:
    responses:
      201:
        description: New user was added.
        body:
          schema: user
      400:
        description: Synax error in JSON.
        body:
          schema: error
  /{userId}:
    uriParameters:
      userId:
        type: string
        required: true
    get:
      responses:
        200:
          description: Retrieve a single user.
          body:
            schema: user
        404:
          description: The user ID doesn't exist.
          body:
            schema: error
    delete:
      responses:
        204:
          description: The user has been evicted.
        404:
          description: The user ID doesn't exist.
          body:
            schema: error
    put:
      responses:
        204:
          description: The user has been updated.
          body:
            schema: user
        400:
          description: Synax error in JSON.
          body:
            schema: error
        404:
          description: The user ID doesn't exist.
          body:
            schema: error
/hotels:
  get:
    responses:
      200:
        description: Retrieve the list of hotels.
        body:
          schema: hotels
  post:
    responses:
      201:
        description: New hotel was added.
        body:
          schema: hotel
      400:
        description: Synax error in JSON.
        body:
          schema: error
  /{hotelId}:
    uriParameters:
      hotelId:
        type: string
        required: true
    get:
        responses:
          200:
            description: Retrieve a single hotel.
            body:
              schema: hotel
          404:
            description: The hotel ID doesn't exist.
            body:
              schema: error
    delete:
      responses:
        204:
          description: The hotel has been evicted.
        404:
          description: The hotel ID doesn't exist.
          body:
            schema: error
    put:
      responses:
        204:
          description: The hotel has been updated.
          body:
            schema: hotel
        400:
          description: Synax error in JSON.
          body:
            schema: error
        404:
          description: The hotel ID doesn't exist.
          body:
            schema: error
    /rooms:
      get:
        responses:
          200:
            description: Retrieve the list of hotel rooms.
            body:
              schema: rooms
      post:
        responses:
          201:
            description: New room was added.
            body:
              schema: room
          404:
            description: The hotel ID doesn't exist.
            body:
              schema: error
      /{roomId}:
        uriParameters:
          roomId:
            type: string
            required: true
        get:
            responses:
              200:
                description: Retrieve a single room.
                body:
                  schema: room
              404:
                description: The room ID doesn't exist.
                body:
                  schema: error
        delete:
          responses:
            204:
              description: The room has been evicted.
            404:
              description: The room ID doesn't exist.
              body:
                schema: error
        put:
          responses:
            204:
              description: The room has been updated.
              body:
                schema: room
            400:
              description: Synax error in JSON.
              body:
                schema: error
            404:
              description: The room ID doesn't exist.
              body:
                schema: error
/reservations:
  get:
    responses:
      200:
        description: Retrieve the list of reservations.
        body:
          schema: reservations
  post:
    responses:
      201:
        description: New reservation was added.
        body:
          schema: reservation
      404:
        description: The reservation ID doesn't exist.
        body:
          schema: error
  /{reservationId}:
    uriParameters:
      reservationId:
        type: string
        required: true
    get:
        responses:
          200:
            description: Retrieve a single reservation.
            body:
              schema: reservation
          404:
            description: The reservation ID doesn't exist.
            body:
              schema: error
    delete:
      responses:
        204:
          description: The reservation has been evicted.
        404:
          description: The reservation ID doesn't exist.
          body:
            schema: error
    put:
      responses:
        204:
          description: The reservation has been updated.
          body:
            schema: reservation
        400:
          description: Synax error in JSON.
          body:
            schema: error
        404:
          description: The reservation ID doesn't exist.
          body:
            schema: error
